name: Sync to Hugging Face Space

on:
  push:
    branches: [ main, master ] # Berjalan otomatis setiap kamu melakukan git push ke branch main atau master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # GANTI 'NAMA_SPACE_KAMU' dengan nama Space Hugging Face yang kamu buat!
        run: |
          git push --force https://scripthutao:$HF_TOKEN@huggingface.co/spaces/scripthutao/BlackholeAi main
